export const words = ["animal", "banana", "bottle", "bridge", "butter", "button", "candle", "circle", 
"danger", "dinner", "effort", "flower", "forest", "garden", "health", 
"laptop", "little", "monkey", "orange", "pencil", "people", "planet", "pocket", 
"rabbit", "rocket", "school", "silver", "simple", "sister", "summer", "ticket", 
"tomato", "window", "yellow", "bridge", "cheese", "driver", "family", "friend", 
"helper", "island", "jungle", "market", "nature", "online", "pebble", "remote", "rubber", "shadow", 
"square", "street", "tunnel", "winner", "winter","basket", "cactus", "camera", "choice", "coffee", "copper", 
"custom", "desert", "detail", "donate",
"empire", "energy", "enough", "expert", "formal", 
"global", "golden", "ground", "growth", "health", 
"import", "income", "jungle", "kindly", "lawyer", "liquid", "listen", "magnet", "master", 
"mirror", "modern", "motion", "notice", "office", "option"];
